apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: hahaton
spec:
  environments:
    default:
      defaultNamespace: default
      server: https://127.0.0.1:36577
  vars:
    computed:
      - name: replaceHelmValues
        code: |
           local qbecValuesBase = import 'environments/base.libsonnet';
           local substitutedQbecValuesBase = qbecValuesBase.components;
           local stdinBase = std.toString(substitutedQbecValuesBase);
          
           local qbecValuesDefault = import 'environments/default.libsonnet';
           local substitutedQbecValuesDefault = qbecValuesDefault.components;
           local stdinDefault = std.toString(substitutedQbecValuesDefault);

           local combinedStdin = stdinDefault + stdinBase;
           {
            command: 'helm',
            args: ['template', '--dry-run', '-f', '-','/home/master/nginx'],
            env: {},
            stdin: combinedStdin,
           } 
  dataSources:
    - exec://helmApiResources?configVar=replaceHelmValues
